<?php $shippingMethod = $this->getShippingMethod(); ?>

<div id="order-shipping_method" class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <div style="float: right;"></div>
            <h4 class="fieldset-legend head-shipping-method icon-head">Shipping Method</h4>
            <div class="form-buttons">
                <button id="submit_order_top_button" type="button" onclick="changeAction('<?php echo $this->getShippingMethodUrl() ?>');" class="scalable save">
                    <span><span><span>Update</span></span></span>
                </button>
            </div>
        </div>
        <div class="fieldset">
            <div id="order-shipping-method-summary">
                <?php if ($shippingMethod) : ?>
                    <?php foreach ($shippingMethod as $key => $value) : ?>
                        <input type="radio" name="shippingMethod" value="<?php echo $value->getId().'_'.$value->getConfigData('price'); ?>" <?php if($value->getId() == $this->fetchShippingMethod()){echo "checked";} ?>>
                        <?php echo $value->getConfigData('name'); ?>
                        <?php echo ' ('.$value->getConfigData('price').' $)'; ?>
                        <br>
                    <?php endforeach; ?>
                <?php else : ?>
                    <label for="p_method_free">No shipping Method Available</label>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
</div>
<div class="clear"></div>